### ISSUE TITLE
Unresolved EF.click() when transaction_id is empty string

### ISSUE THREAD

**Issue by furcic** [everflow-io/everflow-sdk#7]
I have a problem where EF.click() will return a transaction_id === '' In this case the Promise EF.Click is never resolved. 

https://github.com/everflow-io/everflow-sdk/blob/0ddfd41a3bb820c7a07e245afd5ff7d60566b3b6/src/sdk.js#L255-L272

**Comment by olivierboucher** [comment]
We know about this issue but can't fix it straight away as it may break other people's setups

**Comment by jonathanbl** [comment]
@furcic as Olivier pointed out, this is something that our support team mentioned last week. Sadly, this isn't something we can just pushed as it may break existing integrations. We will keep that in mind for future releases but for now, we aren't going to change that

**Comment by furcic** [comment]
Yeah, unfortunately you're breaking new implementations without it, because there is no way to know when the click function is resolved when transaction_id is empty

**Comment by jonathanbl** [comment]
Understood, we will keep that in mind for the future
